# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Configure and build
      run: mkdir build && cd build && cmake -DBUILD_TESTS=OFF .. && cmake --build .

  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Configure and build
      run: mkdir build && cd build && cmake -DBUILD_TESTS=ON -DCOVERAGE_CHECK=on .. && cmake --build .
    - name: Run tests
      run: ./build/bin/gtest_all
    - name: Collect coverage data
      run: /usr/bin/lcov --directory ./build --capture --output-file ./build/coverage.info && /usr/bin/lcov --remove ./build/coverage.info "/usr/*" "*/googletest/googletest/*" --output-file ./build/coverage.info
    - name: Show coverage summary
      run: /usr/bin/lcov --list ./build/coverage.info