# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Configure and build
      run: mkdir build && cd build && cmake -DBUILD_TESTS=ON .. && cmake --build .
    - name: Run tests
      run: ./build/bin/gtest_all
